all : testLinkedStack testLinkedQueue testLinkedList testLinkedList2 testLinkedListO testLinkedListO2

testLinkedStack : testLinkedStack.cpp
	g++ testLinkedStack.cpp -o testLinkedStack -O2 -static-libgcc -static-libstdc++
testLinkedQueue : testLinkedQueue.cpp
	g++ testLinkedQueue.cpp -o testLinkedQueue -O2 -static-libgcc -static-libstdc++
testLinkedList : testLinkedList.cpp
	g++ testLinkedList.cpp -o testLinkedList -O2 -static-libgcc -static-libstdc++
testLinkedList2 : testLinkedList2.cpp
	g++ testLinkedList2.cpp -o testLinkedList2 -O2 -static-libgcc -static-libstdc++
testLinkedListO : testLinkedListO.cpp
	g++ testLinkedListO.cpp -o testLinkedListO -O2 -static-libgcc -static-libstdc++
testLinkedListO2 : testLinkedListO2.cpp
	g++ testLinkedListO2.cpp -o testLinkedListO2 -O2 -static-libgcc -static-libstdc++
